<?php
/**
 * AudioTracksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bol\Retailer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v9 - Retailer API
 *
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 9.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Bol\Retailer;

/**
 * AudioTracksTest Class Doc Comment
 *
 * @category    Class
 * @description AudioTracks
 * @package     Bol\Retailer
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AudioTracksTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AudioTracks"
     */
    public function testAudioTracks()
    {
    }

    /**
     * Test attribute "disc_number"
     */
    public function testPropertyDiscNumber()
    {
    }

    /**
     * Test attribute "track_number"
     */
    public function testPropertyTrackNumber()
    {
    }

    /**
     * Test attribute "disc_side"
     */
    public function testPropertyDiscSide()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "artist_name"
     */
    public function testPropertyArtistName()
    {
    }

    /**
     * Test attribute "play_time"
     */
    public function testPropertyPlayTime()
    {
    }

    /**
     * Test attribute "clip_url"
     */
    public function testPropertyClipUrl()
    {
    }

    /**
     * Test attribute "clip_type"
     */
    public function testPropertyClipType()
    {
    }
}
