<?php
/**
 * DeliveryOptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bol\Retailer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v9 - Retailer API
 *
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 9.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Bol\Retailer;

/**
 * DeliveryOptionTest Class Doc Comment
 *
 * @category    Class
 * @description A delivery option shows how and the costs of a transport for a shippable configuration
 * @package     Bol\Retailer
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DeliveryOptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DeliveryOption"
     */
    public function testDeliveryOption()
    {
    }

    /**
     * Test attribute "shipping_label_offer_id"
     */
    public function testPropertyShippingLabelOfferId()
    {
    }

    /**
     * Test attribute "recommended"
     */
    public function testPropertyRecommended()
    {
    }

    /**
     * Test attribute "valid_until_date"
     */
    public function testPropertyValidUntilDate()
    {
    }

    /**
     * Test attribute "transporter_code"
     */
    public function testPropertyTransporterCode()
    {
    }

    /**
     * Test attribute "label_type"
     */
    public function testPropertyLabelType()
    {
    }

    /**
     * Test attribute "label_display_name"
     */
    public function testPropertyLabelDisplayName()
    {
    }

    /**
     * Test attribute "label_price"
     */
    public function testPropertyLabelPrice()
    {
    }

    /**
     * Test attribute "package_restrictions"
     */
    public function testPropertyPackageRestrictions()
    {
    }

    /**
     * Test attribute "handover_details"
     */
    public function testPropertyHandoverDetails()
    {
    }
}
