<?php
/**
 * ReducedOrderItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bol\Retailer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v9 - Retailer API
 *
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 9.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Bol\Retailer;

/**
 * ReducedOrderItemTest Class Doc Comment
 *
 * @category    Class
 * @description An order item.
 * @package     Bol\Retailer
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReducedOrderItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReducedOrderItem"
     */
    public function testReducedOrderItem()
    {
    }

    /**
     * Test attribute "order_item_id"
     */
    public function testPropertyOrderItemId()
    {
    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {
    }

    /**
     * Test attribute "fulfilment_method"
     */
    public function testPropertyFulfilmentMethod()
    {
    }

    /**
     * Test attribute "fulfilment_status"
     */
    public function testPropertyFulfilmentStatus()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "quantity_shipped"
     */
    public function testPropertyQuantityShipped()
    {
    }

    /**
     * Test attribute "quantity_cancelled"
     */
    public function testPropertyQuantityCancelled()
    {
    }

    /**
     * Test attribute "cancellation_request"
     */
    public function testPropertyCancellationRequest()
    {
    }

    /**
     * Test attribute "latest_changed_date_time"
     */
    public function testPropertyLatestChangedDateTime()
    {
    }
}
