<?php
/**
 * RetailerReviewTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bol\Retailer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v10 - Retailer API
 *
 * The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html)
 *
 * OpenAPI spec version: 10.x-oas3-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.60
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Bol\Retailer;

use PHPUnit\Framework\TestCase;

/**
 * RetailerReviewTest Class Doc Comment
 *
 * @category    Class
 * @description RetailerReview
 * @package     Bol\Retailer
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RetailerReviewTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RetailerReview"
     */
    public function testRetailerReview()
    {
    }

    /**
     * Test attribute "total_review_count"
     */
    public function testPropertyTotalReviewCount()
    {
    }

    /**
     * Test attribute "approval_percentage"
     */
    public function testPropertyApprovalPercentage()
    {
    }

    /**
     * Test attribute "positive_review_count"
     */
    public function testPropertyPositiveReviewCount()
    {
    }

    /**
     * Test attribute "neutral_review_count"
     */
    public function testPropertyNeutralReviewCount()
    {
    }

    /**
     * Test attribute "negative_review_count"
     */
    public function testPropertyNegativeReviewCount()
    {
    }
}
