<?php
/**
 * OffersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Bol\Retailer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v10 - Retailer API
 *
 * The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html)
 *
 * OpenAPI spec version: 10.x-oas3-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.60
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Bol\Retailer;

use Bol\Retailer\Configuration;
use Bol\Retailer\ApiException;
use Bol\Retailer\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OffersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Bol\Retailer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OffersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteOffer
     *
     * Delete offer by id.
     *
     */
    public function testDeleteOffer()
    {
    }

    /**
     * Test case for getOffer
     *
     * Retrieve an offer by its offer id.
     *
     */
    public function testGetOffer()
    {
    }

    /**
     * Test case for getOfferExport
     *
     * Retrieve an offer export file by report id.
     *
     */
    public function testGetOfferExport()
    {
    }

    /**
     * Test case for getUnpublishedOfferReport
     *
     * Retrieve an unpublished offer report by report id.
     *
     */
    public function testGetUnpublishedOfferReport()
    {
    }

    /**
     * Test case for postOffer
     *
     * Create a new offer.
     *
     */
    public function testPostOffer()
    {
    }

    /**
     * Test case for postOfferExport
     *
     * Request an offer export file.
     *
     */
    public function testPostOfferExport()
    {
    }

    /**
     * Test case for postUnpublishedOfferReport
     *
     * Request an unpublished offer report.
     *
     */
    public function testPostUnpublishedOfferReport()
    {
    }

    /**
     * Test case for putOffer
     *
     * Update an offer.
     *
     */
    public function testPutOffer()
    {
    }

    /**
     * Test case for updateOfferPrice
     *
     * Update price(s) for offer by id.
     *
     */
    public function testUpdateOfferPrice()
    {
    }

    /**
     * Test case for updateOfferStock
     *
     * Update stock for offer by id.
     *
     */
    public function testUpdateOfferStock()
    {
    }
}
