<?php
/**
 * ReplenishmentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Bol\Retailer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v10 - Retailer API
 *
 * The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html)
 *
 * OpenAPI spec version: 10.x-oas3-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.60
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Bol\Retailer;

use Bol\Retailer\Configuration;
use Bol\Retailer\ApiException;
use Bol\Retailer\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReplenishmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Bol\Retailer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReplenishmentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getDeliveryDates
     *
     * Get delivery dates.
     *
     */
    public function testGetDeliveryDates()
    {
    }

    /**
     * Test case for getLoadCarrierLabels
     *
     * Get load carrier labels.
     *
     */
    public function testGetLoadCarrierLabels()
    {
    }

    /**
     * Test case for getPickList
     *
     * Get pick list.
     *
     */
    public function testGetPickList()
    {
    }

    /**
     * Test case for getProductDestinations
     *
     * Get product destinations by product destinations id.
     *
     */
    public function testGetProductDestinations()
    {
    }

    /**
     * Test case for getReplenishment
     *
     * Get a replenishment by replenishment id.
     *
     */
    public function testGetReplenishment()
    {
    }

    /**
     * Test case for getReplenishments
     *
     * Get replenishments.
     *
     */
    public function testGetReplenishments()
    {
    }

    /**
     * Test case for postPickupTimeSlots
     *
     * Post pickup time slots.
     *
     */
    public function testPostPickupTimeSlots()
    {
    }

    /**
     * Test case for postProductLabels
     *
     * Post product labels.
     *
     */
    public function testPostProductLabels()
    {
    }

    /**
     * Test case for postReplenishment
     *
     * Create a replenishment.
     *
     */
    public function testPostReplenishment()
    {
    }

    /**
     * Test case for postRequestProductDestinations
     *
     * Request product destinations.
     *
     */
    public function testPostRequestProductDestinations()
    {
    }

    /**
     * Test case for putReplenishment
     *
     * Update a replenishment by replenishment id.
     *
     */
    public function testPutReplenishment()
    {
    }
}
